name: Check for Code Style Violations
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
    branches:
      - master
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install missing software on ubuntu
        run: sudo apt-get install clang-format

      - name: Code format check
        run: |
          echo "*** running clang-format to check for style violations"
          clang-format --Werror -style=file:$HOME/work/Graphitti/Graphitti/.clang-format `find . -type f \( -iname "*.cpp" -or -iname "*.h" \) ! -path "./Testing/lib/*" ! -path "./ThirdParty/*" ! -path "./docs/*"`
